# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96ec01ba0c26f990dfac54a5389f465f8f0ca4555e795c62c9ba695170503713cdcda747d830c5b338a6ae42a90e8b4fb1f9eb9f6cdaa86220ff6a5057518ed7

test:
  secret_key_base: 36a53a4ac2e110cc9c21cd4864e4255578101200aa86d85416933309cd15d91ae1302567f22d5bcce77b820da1169067d9cab46cada4b796af01c8abec4e534a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
